### PR TITLE
Fix cu126 build: guard cudaMemcpyBatchAsync for CUDA >= 12.8

### PR DESCRIPTION
**Pull request by xwang233**
## Issue
cu126 nightly build fails since #5620 merged. cu128 and cu130 builds are unaffected.

**Build error:**
```
error: 'cudaMemcpyAttributes' was not declared in this scope
error: 'cudaMemcpyFlagPreferOverlapWithCompute' was not declared in this scope  
error: 'cudaMemcpySrcAccessOrderAny' was not declared in this scope
```

## Root Cause
The BatchMemcpy protocol uses CUDA 12.8+ APIs (`cudaMemcpyAttributes`, etc.) but the version guard (`#if CUDA_VERSION >= 13000`) only wrapped the function call, not the type declarations. These types don't exist in CUDA 12.6.

## Fix
- Move guard to wrap entire BatchMemcpy block (types + call)
- Change threshold: `>= 13000` → `>= 12080` (APIs introduced in CUDA 12.8)
- Remove broken `#else` branch with `failIdx` parameter

## Behavior

| CUDA Version | Before #5620 | After #5620 | After Fix |
|--------------|--------------|-------------|-----------|
| **12.6 (cu126)** | ✅ cudaMemcpyAsync() | ❌ Compilation error | ✅ cudaMemcpyAsync() fallback |
| **12.8 (cu128)** | ✅ cudaMemcpyAsync() | ✅ cudaMemcpyBatchAsync() | ✅ cudaMemcpyBatchAsync() |
| **13.0 (cu130)** | ✅ cudaMemcpyAsync() | ✅ cudaMemcpyBatchAsync() | ✅ cudaMemcpyBatchAsync() |

CUDA < 12.8: BatchMemcpy protocol disabled at compile time, falls back to standard `cudaMemcpyAsync()`.

## Reference
- `cudaMemcpyBatchAsync` with attributes API introduced in CUDA 12.8
- Related commit: a785d6c9c

---
**Note:** This patch is AI-generated.

### CODE REVIEW

**Comment by xwang233** [comment]
!test

**Comment by xwang233** [comment]
cc @samnordmann can you help fix this issue? Seems like AI patch doesn't work.
