### ISSUE TITLE
nvfuser var_mean crashes

### ISSUE THREAD

**Issue by tfogal** [NVIDIA/Fuser#1835]
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id0(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, 1, -1], contiguity=[True, None, True], dtype=DataType.Half, is_cpu=False, stride_order=[2, 1, 0])
    S1 = fd.define_scalar(None, dtype=DataType.Int)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Bool)
    T4 = fd.ops.cast(T0, dtype=DataType.Float)
    T5, T6 = fd.ops.var_mean(T4, dims=[1], correction=1, keepdim=False)
    T7 = fd.ops.cast(T5, dtype=DataType.Half)
    T8 = fd.ops.cast(T6, dtype=DataType.Half)
    fd.add_output(T7)
    fd.add_output(T8)

with FusionDefinition() as fd:
    nvfuser_fusion_id0(fd)

inputs = [
    torch.randn((48,), dtype=torch.float16, device='cuda:0').as_strided((8, 1, 6), (6, 6, 1)),
    1,
    1,
    False,
]
fd.execute(inputs)
```
> RuntimeError: inferred_val.hasValue() INTERNAL ASSERT FAILED at "/opt/pytorch/nvfuser/csrc/executor.cpp":565, please report a bug with repro script to NVFuser at https://github.com/NVIDIA/Fuser/issues. Could not launch kernel as program could not infer i0(i0) for the buffer T6_g[ iS14{i0}, iS15{i2} ]                                                                       
Exception raised from inferShape at /opt/pytorch/nvfuser/csrc/executor.cpp:565 (most recent call first):

Second (maybe related):
```python
import torch
from nvfuser import FusionDefinition, DataType

def nvfuser_fusion_id1860(fd : FusionDefinition) -> None :
    T0 = fd.define_tensor(shape=[-1, 1, -1], contiguity=[True, None, True], dtype=DataType.BFloat16,
 is_cpu=False, stride_order=[2, 1, 0])
    S1 = fd.define_scalar(None, dtype=DataType.Int)
    S2 = fd.define_scalar(None, dtype=DataType.Int)
    S3 = fd.define_scalar(None, dtype=DataType.Bool)
    T4 = fd.ops.cast(T0, dtype=DataType.Float)
    T5, T6 = fd.ops.var_mean(T4, dims=[1], correction=1, keepdim=False)
    T7 = fd.ops.cast(T5, dtype=DataType.BFloat16)
    T8 = fd.ops.cast(T6, dtype=DataType.BFloat16)
    fd.add_output(T7)
    fd.add_output(T8)

with FusionDefinition() as fd:
    nvfuser_fusion_id1860(fd)

inputs = [
    torch.randn((48,), dtype=torch.bfloat16, device='cuda:0').as_strided((8, 1, 6), (6, 6, 1)),
    1,
    1,
    False,
]
fd.execute(inputs)
```

**Comment by jacobhinkle** [comment]
First repro preseg fusion looks fine to me:
```
Fusion IR after pre-segmenter optimization passes:
Inputs:
  T0_g[ iS0{i0}, bS1{1}, iS2{i2} ], __half
  i5, int64_t
  i6, int64_t
  b7, bool
Outputs:
  T6_g[ iS14{i0}, iS15{i2} ], __half
  T7_g[ iS16{i0}, iS17{i2} ], __half

%kernel_math {
T4_l[ iS10{i0}, iS11{i2} ]
   = full({i0, i2}, float(0));
d14 = (double)(1);
d16 = double(1) * d14;
d20 = (double)(1);
d22 = d16 - d20;
d24 = (double)(0);
b26 = d22 >= d24;
d28 = (double)(0);
d30 = where(b26, d22, d28);
d37 = reciprocal(d30);
T5_l[ iS12{i0}, iS13{i2} ]
   = T4_l[ iS10{i0}, iS11{i2} ]
   * d37;
T6_g[ iS14{i0}, iS15{i2} ]
   = __float2half(T5_l[ iS12{i0}, iS13{i2} ]);
T1_l[ iS3{i0}, bS4{1}, iS5{i2} ]
   = __half2float(T0_g[ iS0{i0}, bS1{1}, iS2{i2} ]);
T2_l[ iS6{i0}, iS7{i2} ]
   = squeeze( T1_l[ iS3{i0}, bS4{1}, iS5{i2} ] )
T7_g[ iS16{i0}, iS17{i2} ]
   = __float2half(T2_l[ iS6{i0}, iS7{i2} ]);
}
```
But then we wind up with two segments
```
Inputs:
  T0_g[ iS0{i0}, bS1{1}, iS2{i2} ], __half
Outputs:
  T7_g[ iS16{i0}, iS17{i2} ], __half

%kernel_math {
T1_g[ iS3{i0}, bS4{1}, iS5{i2} ]
   = __half2float(T0_g[ iS0{i0}, bS1{1}, iS2{i2} ]);
T2_l[ iS6{i0}, iS7{i2} ]
   = squeeze( T1_g[ iS3{i0}, bS4{1}, iS5{i2} ] )
T7_g[ iS16{i0}, iS17{i2} ]
   = __float2half(T2_l[ iS6{i0}, iS7{i2} ]);
}

Inputs:
Outputs:
  T6_g[ iS14{i0}, iS15{i2} ], __half

%kernel_math {
T4_l[ iS10{i0}, iS11{i2} ]
   = full({i0, i2}, float(0));
d14 = (double)(1);
d16 = double(1) * d14;
d20 = (double)(1);
d22 = d16 - d20;
d24 = (double)(0);
b26 = d22 >= d24;
d28 = (double)(0);
d30 = where(b26, d22, d28);
d37 = reciprocal(d30);
T5_l[ iS12{i0}, iS13{i2} ]
   = T4_l[ iS10{i0}, iS11{i2} ]
   * d37;
T6_g[ iS14{i0}, iS15{i2} ]
   = __float2half(T5_l[ iS12{i0}, iS13{i2} ]);
}
```
In the second segment, we have lost the `i0` and `i1` scalars that came from `T0_g` since it is not an input to this segment.

cc @wujingyue I suspect this is related to #1813.

**Comment by wujingyue** [comment]
I tried to revert #1813 but it didn't help fix the reproducer. 

```
commit 96f98a93b58f462c06c209fae8224ccee0ca327f (HEAD -> main)
Author: Jingyue Wu <wujingyue@gmail.com>
Date:   Mon Feb 26 21:21:25 2024 +0000

    Revert "Fix a bug in input forwarding.  (#1813)"
    
    This reverts commit 925acc63e5870718ab83de911ec7f85d6126f729.

commit 417ec4b4bd7f2020b11388ce7d6ba0ae3cc40b6b (origin/main, origin/HEAD)
Author: samnordmann <snordmann@nvidia.com>
Date:   Mon Feb 26 18:26:42 2024 +0100

    Correct typo in MultiDeviceExecutor::print (#1831)
    
    fix build error
    ```
    csrc/multidevice/executor.cpp:268:7: error: variable 'communication_counter' set but not used [-Werror,-Wunused-but-set-variable]
      int communication_counter = 0;
          ^
    ```
    
    Thanks @naoyam 

```

**Comment by wujingyue** [comment]
The problem mentioned in https://github.com/NVIDIA/Fuser/issues/1835#issuecomment-1965279329 seems to be quite similar to https://github.com/NVIDIA/Fuser/issues/1279 -- scalars used in a segment are defined in another segment.

**Comment by jacobhinkle** [comment]
Thanks for checking. You're right this is pretty much the exact repro from #1279. This seems to be a dupe.

**Comment by jacobhinkle** [comment]
Closing as this seems like a duplicate of #1279.
